# Change these first
owner: matheusot # Your GitHub organization or username, where this repository lives
repo: upptime-monitor # The name of this repository

sites:
  - name: Atis Cleaning
    url: https://atiscleaning.com
  - name: Atis Consults
    url: https://atisconsults.com
  - name: Connect Notice
    url: https://connectnotice.com
  - name: Local Locksmith Sandy
    url: https://locallocksmithsandy.com
  - name: LockTheSmith
    url: https://lockthesmith.com
  - name: LockTheSmith UT
    url: https://lockthesmithut.com
  - name: Marcos Locksmith
    url: https://marcoslocksmithservice.com
  - name: Matheus Rodrigues
    url: https://matheusrodrigues.com.br
  - name: Sandy Local Locksmith
    url: https://locallocksmithsandy.com
  - name: Terry Ironwood
    url: https://terryironwood.com
  - name: Tim The Safecracker
    url: https://timthesafecracker.com
  - name: Wevelop
    url: https://wevelop.com.br
  - name: Wvlp
    url: https://wvlp.com.br
  - name: Miazi Media
    url: https://miazimedia.com
  - name: The Papa High
    url: https://thepapahigh.com
  - name: Viamerica
    url: https://viamerica.com.br
  - name: ViaMiazi
    url: https://viamiazi.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
